# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 425)
        Form.setMinimumSize(QtCore.QSize(625, 425))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.net_address = QtWidgets.QLineEdit(self.groupBox)
        self.net_address.setEnabled(False)
        self.net_address.setObjectName("net_address")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.net_address)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.mask = QtWidgets.QLineEdit(self.groupBox)
        self.mask.setEnabled(False)
        self.mask.setObjectName("mask")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mask)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.broadcasting = QtWidgets.QLineEdit(self.groupBox)
        self.broadcasting.setEnabled(False)
        self.broadcasting.setObjectName("broadcasting")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.broadcasting)
        self.dns = QtWidgets.QLineEdit(self.groupBox)
        self.dns.setEnabled(False)
        self.dns.setObjectName("dns")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dns)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_2)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 2, 1, 1)
        self.netMap = QtWidgets.QTableWidget(Form)
        self.netMap.setObjectName("netMap")
        self.netMap.setColumnCount(0)
        self.netMap.setRowCount(0)
        self.gridLayout.addWidget(self.netMap, 3, 0, 1, 3)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.address_begin = QtWidgets.QLineEdit(self.groupBox_2)
        self.address_begin.setObjectName("address_begin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.address_begin)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.address_end = QtWidgets.QLineEdit(self.groupBox_2)
        self.address_end.setObjectName("address_end")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.address_end)
        self.get_information = QtWidgets.QPushButton(self.groupBox_2)
        self.get_information.setObjectName("get_information")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.get_information)
        self.analys = QtWidgets.QPushButton(self.groupBox_2)
        self.analys.setObjectName("analys")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.analys)
        self.hide_timeouted = QtWidgets.QCheckBox(self.groupBox_2)
        self.hide_timeouted.setObjectName("hide_timeouted")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.hide_timeouted)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeout = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeout.sizePolicy().hasHeightForWidth())
        self.timeout.setSizePolicy(sizePolicy)
        self.timeout.setObjectName("timeout")
        self.horizontalLayout.addWidget(self.timeout)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton, self.netMap)
        Form.setTabOrder(self.netMap, self.net_address)
        Form.setTabOrder(self.net_address, self.mask)
        Form.setTabOrder(self.mask, self.broadcasting)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Анализ:"))
        self.label_3.setText(_translate("Form", "Адрес сети"))
        self.label_4.setText(_translate("Form", "Маска"))
        self.label_8.setText(_translate("Form", "DNS:"))
        self.label_5.setText(_translate("Form", "Широковещательный адрес:"))
        self.pushButton.setText(_translate("Form", "Закрыть"))
        self.groupBox_2.setTitle(_translate("Form", "Входные данные:"))
        self.label.setText(_translate("Form", "Начальный адрес"))
        self.address_begin.setText(_translate("Form", "192.168.1.0"))
        self.label_2.setText(_translate("Form", "Конечный адрес"))
        self.address_end.setText(_translate("Form", "192.168.1.255"))
        self.get_information.setText(_translate("Form", "Сбор информации"))
        self.analys.setText(_translate("Form", "Анализ подсети"))
        self.hide_timeouted.setText(_translate("Form", "Скрыть не отвечающие адреса"))
        self.label_6.setText(_translate("Form", "Таймаут:"))
        self.timeout.setText(_translate("Form", "500"))
        self.label_7.setText(_translate("Form", "msec."))

